# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - feature/*
pool:
  vmImage: "ubuntu-latest"

steps:
  - script: echo "Starting CI Pipeline..."
    displayName: "Start"

  - script: npm ci
    displayName: "Install Dependencies"

  - script: npm run lint
    displayName: "Run Linter"

  - script: npm test -- --ci --coverage
    displayName: "Run Tests"

  - script: echo "Build and tests completed successfully."
    displayName: "Finish"
