# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - feature/*
pool:
  vmImage: "ubuntu-latest"

steps:
  - script: echo "Starting CI Pipeline..."
    displayName: "Start"

  - script: npm ci
    displayName: "Install Dependencies"

  - script: npm run lint
    displayName: "Run Linter"

  - script: npm test -- --ci --coverage
    displayName: "Run Tests"

  - task: PublishTestResults@2
    displayName: "Publish Test & Coverage Results"
    inputs:
      testResultsFiles: "**/*junit.xml"
      testRunTitle: "Unit Tests"
      mergeTestResults: true

  - task: PublishCodeCoverageResults@2
    displayName: "Publish Code Coverage"
    inputs:
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml"

  - script: echo "Build and tests completed successfully."
    displayName: "Finish"
